### ISSUE TITLE
WayArts logo creative work

### ISSUE THREAD

**Issue by sahlet-official** [sahlet-official/sleeplog#79]
- [x] Draw
- [x] Review

______________

This issue size:
- Estimate SP: 3
- Actual SP: 3

**Comment by varunpenumudi** [comment]
Hi do you want someone to make a logo for your app

**Comment by sahlet-official** [comment]
Hello.

We are already making a logo.
But if you have some ideas - welcome

**Comment by varunpenumudi** [comment]
Hey i am a graphic designer i want to help you with design, but can i know more about the project and app, is there a apk file to try it out. And how can i submit my ideas

**Comment by varunpenumudi** [comment]
I can also make good documentation for your repository if get more information.

**Comment by sahlet-official** [comment]
We are working on the first app.
There's still no apk.

The idea is that there i way (life) and people can turn the process of
living into art.
One of the projects (for now it's only one) is log project.

Idea of log project is that you can log everything you want, and then watch
it as log.
Like accounting of life.

Ander this idea we can create log apps for different topics.
Like Foodlog, Moodlog, Actionlog, Sleeplog...

**Comment by varunpenumudi** [comment]
So it is like a habit tracker

**Comment by sahlet-official** [comment]
No, it's like business accounting but it's life accounting

**Comment by varunpenumudi** [comment]
Can i see any draft logo designs made before
